DROP TABLE IF EXISTS VON;
DROP TABLE IF EXISTS ENTHAELT;
DROP TABLE IF EXISTS HASHTAG;
DROP TABLE IF EXISTS AUTOR;
DROP TABLE IF EXISTS TWEET;

CREATE TABLE TWEET(
	ID SERIAL PRIMARY KEY,
	Text text NOT NULL,
	Time date,
	Favourite integer,
	Retweet_count integer,
	Link text
);

CREATE TABLE HASHTAG(
	Name text PRIMARY KEY	
);

CREATE TABLE AUTOR(
	Username text PRIMARY KEY
);

CREATE TABLE VON(
	TID integer REFERENCES TWEET(ID),
	Username text REFERENCES AUTOR(Username),
	Original text,
	PRIMARY KEY(TID, Username)
);

CREATE TABLE ENTHAELT(
	TID integer REFERENCES TWEET(ID),
	HName text REFERENCES HASHTAG(Name),
	PRIMARY KEY(TID, HName)
);


